namespace Logic
{
    public enum ESkill
    {
        Athletics,
        Brawl,
        Craft,
        Drive,
        Firearms,
        Larceny,
        Melee,
        Stealth,
        Survival,
        AnimalKen,
        Etiquette,
        Insight,
        Intimidation,
        Leadership,
        Performance,
        Persuasion,
        Streetwise,
        Subterfuge,
        Academics,
        Awareness,
        Finance,
        Investigation,
        Medicine,
        Occult,
        Politics,
        Science,
        Technology,
    }
}